name: 'Dockerfiles matrix generator'
description: 'Generate job matrix for all Dockerfiles in the project'
inputs:
  paths:
    description: 'Paths where to look for Dockerfiles'
    required: false
    default: '**/Dockerfile'
outputs:
  matrix:
    description: 'Job matrix'
runs:
  using: 'node12'
  main: 'dist/index.js'
