name: 'Dockerfiles matrix generator'
description: 'Generate job matrix for all Dockerfiles in the project'
inputs:
  image-name:
    description: 'Custom image name'
    required: false
  latest-branch:
    description: 'Name of the branch to associate with the "latest" tag'
    required: false
    default: 'master'
  paths:
    description: 'Paths where to look for Dockerfiles'
    required: false
    default: '.'
  recursive:
    description: 'Search for Dockerfiles recursively'
    required: false
    default: 'false'
outputs:
  matrix:
    description: 'Job matrix'
runs:
  using: 'node12'
  main: 'dist/index.js'
