name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test_action:
    name: Test action
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Generate matrix
        id: matrix
        uses: ./
        with:
          paths: |
            test/alt
            test/docker
          recursive: true
      - name: Validate JSON
        run: echo '${{ steps.matrix.outputs.matrix }}' | jq '.'
      - name: Check for expected result
        run: >
          test '${{ steps.matrix.outputs.matrix }}' =
          '{"include":[{"cache-path":"drugscom/docker-matrix-action","dockerfile":"/home/runner/work/docker-matrix-action/docker-matrix-action/test/docker/Dockerfile","image-name":"ghcr.io/drugscom/docker-matrix-action:latest","tags":"ghcr.io/drugscom/docker-matrix-action:latest"},{"cache-path":"drugscom/docker-matrix-action/alpine","dockerfile":"/home/runner/work/docker-matrix-action/docker-matrix-action/test/docker/alpine/Dockerfile","image-name":"ghcr.io/drugscom/docker-matrix-action:latest-alpine","tags":"ghcr.io/drugscom/docker-matrix-action:latest-alpine"},{"cache-path":"drugscom/docker-matrix-action/production","dockerfile":"/home/runner/work/docker-matrix-action/docker-matrix-action/test/docker/production/Dockerfile","image-name":"ghcr.io/drugscom/docker-matrix-action:latest-production","tags":"ghcr.io/drugscom/docker-matrix-action:latest-production"},{"cache-path":"drugscom/docker-matrix-action/production/alpine","dockerfile":"/home/runner/work/docker-matrix-action/docker-matrix-action/test/docker/production/alpine/Dockerfile","image-name":"ghcr.io/drugscom/docker-matrix-action:latest-production-alpine","tags":"ghcr.io/drugscom/docker-matrix-action:latest-production-alpine"}]}'
