name: Testing

on:
  workflow_dispatch:
  push:

jobs:
  test_action:
    name: Test action
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate matrix
        id: matrix
        uses: ./
        with:
          paths: |
            test/alt
            test/docker
          recursive: true
      - name: Validate JSON
        run: echo '${{ steps.matrix.outputs.matrix }}' | jq '.'
      - name: Check for expected result
        run: >
          test '${{ steps.matrix.outputs.matrix }}' =
          '{"include":[{"cache-path":"drugscom/docker-matrix-action/test/docker/alpine","dockerfile":"test/docker/alpine/Dockerfile","image-name":"drugscom/docker-matrix-action:latest-alpine","tags":"drugscom/docker-matrix-action:latest-alpine"},{"cache-path":"drugscom/docker-matrix-action/test/docker","dockerfile":"test/docker/Dockerfile","image-name":"drugscom/docker-matrix-action:latest","tags":"drugscom/docker-matrix-action:latest"},{"cache-path":"drugscom/docker-matrix-action/test/docker/production/alpine","dockerfile":"test/docker/production/alpine/Dockerfile","image-name":"drugscom/docker-matrix-action:latest-production-alpine","tags":"drugscom/docker-matrix-action:latest-production-alpine"},{"cache-path":"drugscom/docker-matrix-action/test/docker/production","dockerfile":"test/docker/production/Dockerfile","image-name":"drugscom/docker-matrix-action:latest-production","tags":"drugscom/docker-matrix-action:latest-production"}]}'
